// Mock dataset for the Backline prototype — a fictional Austin, TX scene.
// In production this comes from the API; the shapes in types.ts are the contract.

import type {
  Band,
  Conversation,
  FeedPost,
  Gig,
  Musician,
  Venue,
} from "./types";

// ---------------------------------------------------------------- musicians

export const MUSICIANS: Musician[] = [
  {
    id: "m-dre",
    name: "Dre Okafor",
    handle: "dreonthedrums",
    instruments: [{ id: "drums", level: "pro", years: 12 }],
    genres: ["Funk", "Soul", "Hip-Hop"],
    bio: "Pocket-first drummer. 12 years touring and session work — if the groove doesn't move you, I'm not done yet. Sub-friendly: send me a setlist and I'm chart-ready in a day.",
    gear: ["Gretsch Brooklyn 4-pc", "Istanbul Agop cymbals", "SPD-SX pad", "In-ears + own mics"],
    neighborhood: "East Austin",
    distanceMiles: 1.2,
    rate: { min: 120, max: 200 },
    availableTonight: true,
    availability: ["Thu", "Fri", "Sat", "Sun"],
    responseMins: 8,
    gigsPlayed: 214,
    verified: true,
    videos: [
      { id: "v-dre-1", title: "Pocket groove @ 92bpm", durationSec: 34, plays: 12800, likes: 1430, palette: ["#f59e0b", "#7c2d12"], tags: ["funk", "pocket"] },
      { id: "v-dre-2", title: "Half-time shuffle breakdown", durationSec: 51, plays: 8900, likes: 990, palette: ["#ef4444", "#1e1b4b"], tags: ["shuffle", "lesson"] },
      { id: "v-dre-3", title: "Live at Sunset Ballroom", durationSec: 45, plays: 21400, likes: 2100, palette: ["#8b5cf6", "#0c0a09"], tags: ["live"] },
    ],
    reviews: [
      { id: "r-dre-1", author: "Cass Monroe", role: "Bandleader, Velvet Hour", rating: 5, text: "Called Dre at 4pm for an 8pm downbeat. He walked in with the set memorized. Unreal.", date: "Jun 2026" },
      { id: "r-dre-2", author: "Prickly Pear Listening Room", role: "Venue", rating: 5, text: "Professional, on time, great with our sound tech. Booked him three more times.", date: "May 2026" },
    ],
    bandIds: ["b-brasshouse"],
    seed: 1,
  },
  {
    id: "m-sam",
    name: "Sam Reyes",
    handle: "samreyespercussion",
    instruments: [
      { id: "drums", level: "pro", years: 9 },
      { id: "vocals", level: "semi-pro", years: 4 },
    ],
    genres: ["Latin", "Rock", "Cumbia"],
    bio: "Drummer + percussionist (timbales, congas, cajón). Comfortable singing backups. I keep a car kit packed — can be anywhere in town within the hour.",
    gear: ["Yamaha Stage Custom", "Timbales + congas", "Cajón for acoustic sets"],
    neighborhood: "South Congress",
    distanceMiles: 3.4,
    rate: { min: 100, max: 160 },
    availableTonight: true,
    availability: ["Wed", "Fri", "Sat"],
    responseMins: 15,
    gigsPlayed: 156,
    verified: true,
    videos: [
      { id: "v-sam-1", title: "Cumbia groove, full kit", durationSec: 28, plays: 6400, likes: 720, palette: ["#10b981", "#78350f"], tags: ["cumbia"] },
      { id: "v-sam-2", title: "Timbales solo (loud!)", durationSec: 39, plays: 15200, likes: 1800, palette: ["#f97316", "#312e81"], tags: ["latin", "solo"] },
    ],
    reviews: [
      { id: "r-sam-1", author: "Luz Herrera", role: "Guitarist, Cedar & Rye", rating: 5, text: "Sat in with zero rehearsal and nailed a 2-hour set. Crowd loved the timbales feature.", date: "Jun 2026" },
    ],
    bandIds: [],
    seed: 2,
  },
  {
    id: "m-katie",
    name: "Katie Lindqvist",
    handle: "katiehitsthings",
    instruments: [{ id: "drums", level: "semi-pro", years: 6 }],
    genres: ["Indie", "Punk", "Garage"],
    bio: "Loud, fast, tasteful when required. Day job in tech so weeknights after 7 and all weekend. I learn sets from voice memos, no charts needed.",
    gear: ["Ludwig Breakbeats (small stages)", "C&C 4-pc (big rooms)"],
    neighborhood: "Hyde Park",
    distanceMiles: 2.8,
    rate: { min: 75, max: 120 },
    availableTonight: false,
    availability: ["Fri", "Sat", "Sun"],
    responseMins: 42,
    gigsPlayed: 88,
    verified: false,
    videos: [
      { id: "v-katie-1", title: "Garage beat, one take", durationSec: 22, plays: 3100, likes: 410, palette: ["#ec4899", "#134e4a"], tags: ["punk"] },
    ],
    reviews: [
      { id: "r-katie-1", author: "Moontower Revival", role: "Band", rating: 5, text: "Katie's our permanent drummer for a reason. Hits like a truck, shows up early.", date: "Apr 2026" },
    ],
    bandIds: ["b-moontower"],
    seed: 3,
  },
  {
    id: "m-jbird",
    name: "J-Bird Tolliver",
    handle: "jbirdbass",
    instruments: [{ id: "bass", level: "pro", years: 15 }],
    genres: ["Funk", "R&B", "Gospel"],
    bio: "Bass is a service industry and I'm here to serve the song. 15 years holding it down. Upright available for jazz/acoustic dates (+$40).",
    gear: ["Fender P-Bass '73", "Upright (3/4)", "Ampeg rig or DI, your call"],
    neighborhood: "East Austin",
    distanceMiles: 1.9,
    rate: { min: 130, max: 220 },
    availableTonight: true,
    availability: ["Thu", "Fri", "Sat"],
    responseMins: 12,
    gigsPlayed: 302,
    verified: true,
    videos: [
      { id: "v-jbird-1", title: "Gospel chops but tasteful", durationSec: 41, plays: 18700, likes: 2400, palette: ["#3b82f6", "#422006"], tags: ["gospel", "groove"] },
      { id: "v-jbird-2", title: "Upright: 'Autumn Leaves'", durationSec: 58, plays: 5200, likes: 610, palette: ["#a16207", "#1c1917"], tags: ["jazz", "upright"] },
    ],
    reviews: [
      { id: "r-jbird-1", author: "Ada Osei", role: "MD, Brass House ATX", rating: 5, text: "The most reliable low end in the city. Reads, improvises, never overplays.", date: "Jun 2026" },
    ],
    bandIds: ["b-brasshouse"],
    seed: 4,
  },
  {
    id: "m-nina",
    name: "Nina Vo",
    handle: "ninavobass",
    instruments: [
      { id: "bass", level: "semi-pro", years: 7 },
      { id: "vocals", level: "semi-pro", years: 7 },
    ],
    genres: ["Indie", "Dream Pop", "Shoegaze"],
    bio: "Bass + lead or backup vocals. I bring the pedals and the harmonies. Currently playing with Moontower Revival, open to fill-ins on off nights.",
    gear: ["Fender Mustang bass", "Pedalboard (chorus-heavy, sorry)"],
    neighborhood: "Cherrywood",
    distanceMiles: 2.1,
    rate: { min: 80, max: 140 },
    availableTonight: false,
    availability: ["Sun", "Mon", "Tue"],
    responseMins: 55,
    gigsPlayed: 74,
    verified: false,
    videos: [
      { id: "v-nina-1", title: "Bass + vox live loop", durationSec: 47, plays: 4400, likes: 580, palette: ["#8b5cf6", "#164e63"], tags: ["dreampop"] },
    ],
    reviews: [],
    bandIds: ["b-moontower"],
    seed: 5,
  },
  {
    id: "m-marcus",
    name: "Marcus Dell",
    handle: "marcusdellblues",
    instruments: [{ id: "guitar", level: "pro", years: 20 }],
    genres: ["Blues", "Rock", "Country"],
    bio: "Two decades of Texas blues. Lead or rhythm, slide on request. I know every blues standard in every key, and I mean that literally.",
    gear: ["'62 Strat reissue", "335 clone", "Deluxe Reverb"],
    neighborhood: "South Lamar",
    distanceMiles: 4.6,
    rate: { min: 110, max: 180 },
    availableTonight: true,
    availability: ["Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    responseMins: 20,
    gigsPlayed: 460,
    verified: true,
    videos: [
      { id: "v-marcus-1", title: "Slow blues in G, one take", durationSec: 55, plays: 9800, likes: 1200, palette: ["#0ea5e9", "#450a0a"], tags: ["blues", "slide"] },
      { id: "v-marcus-2", title: "Chicken pickin' warm-up", durationSec: 31, plays: 7600, likes: 890, palette: ["#eab308", "#14532d"], tags: ["country"] },
    ],
    reviews: [
      { id: "r-marcus-1", author: "The Blue Armadillo", role: "Venue", rating: 5, text: "Marcus has bailed out three bands on our stage this year alone. A scene treasure.", date: "May 2026" },
    ],
    bandIds: ["b-moontower"],
    seed: 6,
  },
  {
    id: "m-luz",
    name: "Luz Herrera",
    handle: "luzsteel",
    instruments: [
      { id: "guitar", level: "pro", years: 11 },
      { id: "pedal-steel", level: "pro", years: 8 },
    ],
    genres: ["Country", "Americana", "Honky-Tonk"],
    bio: "Guitar and pedal steel for your two-steppin' needs. Founding member of Cedar & Rye. Steel adds instant heartbreak to any ballad — booking me is cheaper than therapy.",
    gear: ["Telecaster (obviously)", "GFI pedal steel", "Princeton Reverb"],
    neighborhood: "Bouldin Creek",
    distanceMiles: 3.9,
    rate: { min: 120, max: 190 },
    availableTonight: false,
    availability: ["Fri", "Sat"],
    responseMins: 35,
    gigsPlayed: 240,
    verified: true,
    videos: [
      { id: "v-luz-1", title: "Steel solo: 'Crying Time'", durationSec: 44, plays: 11300, likes: 1500, palette: ["#f43f5e", "#1e3a8a"], tags: ["pedalsteel"] },
    ],
    reviews: [
      { id: "r-luz-1", author: "Rattlesnake Room", role: "Venue", rating: 5, text: "Our Wednesday honky-tonk residency wouldn't exist without Luz.", date: "Jun 2026" },
    ],
    bandIds: ["b-cedarrye"],
    seed: 7,
  },
  {
    id: "m-theo",
    name: "Theo Park",
    handle: "theoparkkeys",
    instruments: [{ id: "keys", level: "pro", years: 14 }],
    genres: ["Jazz", "Soul", "Neo-Soul"],
    bio: "Keys for jazz trios, soul revues, and everything between. Berklee dropout (best decision I ever made). Rhodes, organ, synth bass if your bassist bails too.",
    gear: ["Nord Stage 3", "Crumar Mojo organ", "Own PA for small rooms"],
    neighborhood: "Mueller",
    distanceMiles: 2.5,
    rate: { min: 130, max: 210 },
    availableTonight: true,
    availability: ["Mon", "Thu", "Fri", "Sat"],
    responseMins: 10,
    gigsPlayed: 275,
    verified: true,
    videos: [
      { id: "v-theo-1", title: "Rhodes over neo-soul changes", durationSec: 38, plays: 14100, likes: 1900, palette: ["#14b8a6", "#4c1d95"], tags: ["neosoul", "rhodes"] },
      { id: "v-theo-2", title: "Organ trio burner", durationSec: 49, plays: 6800, likes: 750, palette: ["#f59e0b", "#0f172a"], tags: ["jazz", "organ"] },
    ],
    reviews: [
      { id: "r-theo-1", author: "Velvet Hour", role: "Band", rating: 5, text: "Theo is the reason people think our trio has four members. Huge sound.", date: "Jun 2026" },
    ],
    bandIds: ["b-velvet"],
    seed: 8,
  },
  {
    id: "m-ada",
    name: "Ada Osei",
    handle: "adaosei",
    instruments: [
      { id: "keys", level: "pro", years: 16 },
      { id: "vocals", level: "pro", years: 16 },
    ],
    genres: ["Gospel", "Soul", "R&B"],
    bio: "Music director, keys, and vocals. I run Brass House ATX's horn-driven soul machine. Available for MD work, session dates, and the occasional wedding that pays properly.",
    gear: ["Yamaha CP88", "Full charts library"],
    neighborhood: "Windsor Park",
    distanceMiles: 3.1,
    rate: { min: 150, max: 250 },
    availableTonight: false,
    availability: ["Sat", "Sun"],
    responseMins: 25,
    gigsPlayed: 330,
    verified: true,
    videos: [
      { id: "v-ada-1", title: "Vocal run breakdown 🔥", durationSec: 26, plays: 22800, likes: 3400, palette: ["#d946ef", "#713f12"], tags: ["vocals", "gospel"] },
    ],
    reviews: [
      { id: "r-ada-1", author: "J-Bird Tolliver", role: "Bassist", rating: 5, text: "Best MD I've worked with. Rehearsals run on time and the charts are immaculate.", date: "May 2026" },
    ],
    bandIds: ["b-brasshouse"],
    seed: 9,
  },
  {
    id: "m-cass",
    name: "Cass Monroe",
    handle: "cassmonroe",
    instruments: [{ id: "vocals", level: "pro", years: 10 }],
    genres: ["Jazz", "Soul", "Standards"],
    bio: "Jazz vocalist. Standards, torch songs, and the occasional Bowie cover when the room earns it. Fronting Velvet Hour Thursdays at the Rattlesnake Room.",
    gear: ["Own mic (SM58 Beta + vintage ribbon for studio)"],
    neighborhood: "Clarksville",
    distanceMiles: 4.2,
    rate: { min: 140, max: 230 },
    availableTonight: true,
    availability: ["Thu", "Fri", "Sat"],
    responseMins: 18,
    gigsPlayed: 190,
    verified: true,
    videos: [
      { id: "v-cass-1", title: "'Round Midnight (live)", durationSec: 60, plays: 9400, likes: 1300, palette: ["#6366f1", "#1c1917"], tags: ["jazz", "live"] },
    ],
    reviews: [],
    bandIds: ["b-velvet"],
    seed: 10,
  },
  {
    id: "m-ray",
    name: "Ray Delgado",
    handle: "raydelgadosax",
    instruments: [{ id: "sax", level: "pro", years: 18 }],
    genres: ["Funk", "Jazz", "Ska"],
    bio: "Tenor and alto sax. Horn section arranger — book me and I'll bring charts for your whole section. Ska past, no regrets.",
    gear: ["Selmer Mark VI tenor", "Yamaha alto", "Wireless clip mic"],
    neighborhood: "East Austin",
    distanceMiles: 1.5,
    rate: { min: 100, max: 170 },
    availableTonight: true,
    availability: ["Wed", "Fri", "Sat"],
    responseMins: 30,
    gigsPlayed: 265,
    verified: true,
    videos: [
      { id: "v-ray-1", title: "Tenor solo over 'Cissy Strut'", durationSec: 36, plays: 8100, likes: 940, palette: ["#f97316", "#064e3b"], tags: ["funk", "sax"] },
    ],
    reviews: [],
    bandIds: ["b-brasshouse"],
    seed: 11,
  },
  {
    id: "m-belle",
    name: "Belle Tran",
    handle: "belletran",
    instruments: [{ id: "trumpet", level: "semi-pro", years: 8 }],
    genres: ["Funk", "Latin", "Indie"],
    bio: "Trumpet + flugelhorn. UT music grad. I read anything you put in front of me and I show up warmed up.",
    gear: ["Bach Stradivarius", "Flugelhorn", "Harmon mute for the moody stuff"],
    neighborhood: "North Loop",
    distanceMiles: 3.6,
    rate: { min: 80, max: 140 },
    availableTonight: false,
    availability: ["Fri", "Sat", "Sun"],
    responseMins: 40,
    gigsPlayed: 95,
    verified: false,
    videos: [
      { id: "v-belle-1", title: "Flugel over lofi changes", durationSec: 33, plays: 5600, likes: 720, palette: ["#22d3ee", "#7c2d12"], tags: ["chill"] },
    ],
    reviews: [],
    bandIds: ["b-brasshouse"],
    seed: 12,
  },
  {
    id: "m-ivy",
    name: "Ivy Nakamura",
    handle: "ivyfiddle",
    instruments: [{ id: "violin", level: "pro", years: 13 }],
    genres: ["Folk", "Americana", "Bluegrass"],
    bio: "Fiddle for barn dances, violin for weddings — same instrument, different invoice. Harmony vocals included free of charge.",
    gear: ["5-string fiddle", "Own pickup + preamp"],
    neighborhood: "Zilker",
    distanceMiles: 4.8,
    rate: { min: 90, max: 160 },
    availableTonight: true,
    availability: ["Thu", "Sat", "Sun"],
    responseMins: 22,
    gigsPlayed: 178,
    verified: true,
    videos: [
      { id: "v-ivy-1", title: "Fiddle tune medley", durationSec: 42, plays: 7300, likes: 850, palette: ["#84cc16", "#581c87"], tags: ["bluegrass"] },
    ],
    reviews: [
      { id: "r-ivy-1", author: "Cedar & Rye", role: "Band", rating: 5, text: "Ivy turned our duo set into a real string band. Books fast on weekends.", date: "Jun 2026" },
    ],
    bandIds: ["b-cedarrye"],
    seed: 13,
  },
  {
    id: "m-kilo",
    name: "DJ Kilowatt",
    handle: "djkilowatt",
    instruments: [{ id: "dj", level: "pro", years: 10 }],
    genres: ["House", "Disco", "Hip-Hop"],
    bio: "Open-format DJ + Ableton live sets. I do club nights, band interludes, and after-parties. Own controller, own lights, zero requests for 'Mr. Brightside' honored.",
    gear: ["Pioneer DDJ-1000", "Ableton Push", "Small LX rig"],
    neighborhood: "Downtown",
    distanceMiles: 2.9,
    rate: { min: 150, max: 300 },
    availableTonight: true,
    availability: ["Thu", "Fri", "Sat"],
    responseMins: 14,
    gigsPlayed: 320,
    verified: true,
    videos: [
      { id: "v-kilo-1", title: "Disco edit set, rooftop", durationSec: 57, plays: 16900, likes: 2200, palette: ["#e11d48", "#0c4a6e"], tags: ["house", "live"] },
    ],
    reviews: [],
    bandIds: ["b-nightmarket"],
    seed: 14,
  },
  {
    id: "m-gus",
    name: "Gus Ferreira",
    handle: "gusfoh",
    instruments: [{ id: "sound-tech", level: "pro", years: 17 }],
    genres: ["Live Sound", "FOH", "Monitors"],
    bio: "FOH engineer. I've mixed everything from punk basements to 1,200-cap rooms. Your band sounds better when the person behind the desk cares — I care.",
    gear: ["Own mic locker", "X32 rack for DIY rooms", "RF coordination"],
    neighborhood: "St. Johns",
    distanceMiles: 5.2,
    rate: { min: 150, max: 275 },
    availableTonight: true,
    availability: ["Wed", "Thu", "Fri", "Sat"],
    responseMins: 16,
    gigsPlayed: 410,
    verified: true,
    videos: [
      { id: "v-gus-1", title: "Ringing out monitors 101", durationSec: 48, plays: 4900, likes: 640, palette: ["#64748b", "#701a75"], tags: ["tech", "lesson"] },
    ],
    reviews: [
      { id: "r-gus-1", author: "Warehouse 512", role: "Venue", rating: 5, text: "Gus is our first-call FOH sub. Bands ask for him by name afterward.", date: "Apr 2026" },
    ],
    bandIds: [],
    seed: 15,
  },
  {
    id: "m-pri",
    name: "Priya Anand",
    handle: "priyalights",
    instruments: [{ id: "lighting-tech", level: "semi-pro", years: 5 }],
    genres: ["Lighting", "Visuals", "Projection"],
    bio: "Lighting design + live visuals. I make your $200 bar gig look like a $20 ticket. Touring rig fits in a hatchback.",
    gear: ["4x moving heads", "Hazer", "Resolume rig for projections"],
    neighborhood: "Riverside",
    distanceMiles: 3.8,
    rate: { min: 90, max: 180 },
    availableTonight: false,
    availability: ["Fri", "Sat"],
    responseMins: 50,
    gigsPlayed: 120,
    verified: false,
    videos: [
      { id: "v-pri-1", title: "Before/after: bar stage glow-up", durationSec: 29, plays: 10300, likes: 1600, palette: ["#a855f7", "#0e7490"], tags: ["lighting"] },
    ],
    reviews: [],
    bandIds: ["b-nightmarket"],
    seed: 16,
  },
];

// -------------------------------------------------------------------- bands

export const BANDS: Band[] = [
  {
    id: "b-moontower",
    name: "Moontower Revival",
    genres: ["Indie Rock", "Garage"],
    bio: "Four-piece indie rock. Loud guitars, louder feelings. Debut EP 'Porch Light' out now — recorded live in a garage in Hyde Park, and it sounds like it (on purpose).",
    neighborhood: "Hyde Park",
    members: [
      { musicianId: "m-katie", role: "Drums" },
      { musicianId: "m-nina", role: "Bass / Vocals" },
      { musicianId: "m-marcus", role: "Guitar" },
    ],
    openSlots: [{ instrument: "keys", note: "Synth/organ for fall tour. Must tolerate van smell." }],
    followers: 1840,
    gigIds: ["g-moontower-armadillo"],
    seed: 21,
  },
  {
    id: "b-brasshouse",
    name: "Brass House ATX",
    genres: ["Funk", "Soul", "Brass"],
    bio: "Nine-piece horn-driven funk machine, MD'd by Ada Osei. We play weddings that want to feel like block parties and block parties that want to feel like weddings.",
    neighborhood: "East Austin",
    members: [
      { musicianId: "m-ada", role: "MD / Keys / Vocals" },
      { musicianId: "m-dre", role: "Drums" },
      { musicianId: "m-jbird", role: "Bass" },
      { musicianId: "m-ray", role: "Tenor Sax" },
      { musicianId: "m-belle", role: "Trumpet" },
    ],
    openSlots: [{ instrument: "sound-tech", note: "Regular FOH for 2-3 gigs/month. We travel with charts and stems." }],
    followers: 4620,
    gigIds: ["g-brasshouse-sunset"],
    seed: 22,
  },
  {
    id: "b-cedarrye",
    name: "Cedar & Rye",
    genres: ["Country", "Americana"],
    bio: "Honky-tonk with a songwriter's heart. Wednesday residency at the Rattlesnake Room. Bring your boots, or don't, we're not the dress code police.",
    neighborhood: "Bouldin Creek",
    members: [
      { musicianId: "m-luz", role: "Guitar / Pedal Steel" },
      { musicianId: "m-ivy", role: "Fiddle" },
    ],
    openSlots: [
      { instrument: "drums", note: "URGENT: our drummer's van died in Waco. Need a sub for TONIGHT, 9pm, Rattlesnake Room. Brushes-friendly." },
      { instrument: "bass", note: "Permanent slot. Upright a plus, harmony vocals a bigger plus." },
    ],
    followers: 2310,
    gigIds: ["g-cedarrye-rattlesnake"],
    seed: 23,
  },
  {
    id: "b-velvet",
    name: "Velvet Hour",
    genres: ["Jazz", "Soul"],
    bio: "Late-night jazz for people who talk quietly in bars. Cass Monroe on vocals, Theo Park on keys. Thursdays at the Rattlesnake Room, occasionally somewhere fancier.",
    neighborhood: "Clarksville",
    members: [
      { musicianId: "m-cass", role: "Vocals" },
      { musicianId: "m-theo", role: "Keys" },
    ],
    openSlots: [{ instrument: "bass", note: "Upright preferred for the trio dates. Standards repertoire required." }],
    followers: 1290,
    gigIds: ["g-velvet-prickly"],
    seed: 24,
  },
  {
    id: "b-nightmarket",
    name: "Night Market",
    genres: ["Electronic", "Live House"],
    bio: "DJ Kilowatt + live drums + lights by Priya. Half DJ set, half live band, all sweat. If the floor isn't shaking we issue refunds (we have never issued a refund).",
    neighborhood: "Downtown",
    members: [
      { musicianId: "m-kilo", role: "DJ / Production" },
      { musicianId: "m-pri", role: "Lighting / Visuals" },
    ],
    openSlots: [{ instrument: "vocals", note: "Guest vocalists for club nights. House/disco vibes, tops-lines welcome." }],
    followers: 3480,
    gigIds: ["g-nightmarket-warehouse"],
    seed: 25,
  },
];

// ------------------------------------------------------------------- venues

export const VENUES: Venue[] = [
  { id: "v-armadillo", name: "The Blue Armadillo", neighborhood: "East Austin", capacity: 250, followers: 5200, vibe: "Sticky floors, perfect sound, the best Tuesday crowd in town.", seed: 31 },
  { id: "v-rattlesnake", name: "Rattlesnake Room", neighborhood: "Downtown", capacity: 180, followers: 3900, vibe: "Honky-tonk Wednesdays, jazz Thursdays, chaos Fridays.", seed: 32 },
  { id: "v-sunset", name: "Sunset Ballroom", neighborhood: "South Congress", capacity: 900, followers: 12400, vibe: "The mid-size room every touring band remembers.", seed: 33 },
  { id: "v-prickly", name: "Prickly Pear Listening Room", neighborhood: "Clarksville", capacity: 120, followers: 2100, vibe: "Pin-drop quiet listening room. Phones away, hearts open.", seed: 34 },
  { id: "v-warehouse", name: "Warehouse 512", neighborhood: "Riverside", capacity: 1200, followers: 8800, vibe: "Big room, big system, late nights.", seed: 35 },
];

// --------------------------------------------------------------------- gigs

export const GIGS: Gig[] = [
  { id: "g-cedarrye-rattlesnake", title: "Cedar & Rye — Honky-Tonk Night", venueId: "v-rattlesnake", bandId: "b-cedarrye", date: "Tonight", time: "9:00 PM", payout: 150, ticket: "$10" },
  { id: "g-moontower-armadillo", title: "Moontower Revival EP Release", venueId: "v-armadillo", bandId: "b-moontower", date: "Fri Jul 10", time: "10:00 PM", ticket: "$12" },
  { id: "g-brasshouse-sunset", title: "Brass House ATX + guests", venueId: "v-sunset", bandId: "b-brasshouse", date: "Sat Jul 11", time: "8:30 PM", ticket: "$18" },
  { id: "g-velvet-prickly", title: "Velvet Hour: Standards & Stories", venueId: "v-prickly", bandId: "b-velvet", date: "Thu Jul 9", time: "7:30 PM", ticket: "$15" },
  { id: "g-nightmarket-warehouse", title: "Night Market — All Night Long", venueId: "v-warehouse", bandId: "b-nightmarket", date: "Sat Jul 11", time: "11:00 PM", ticket: "$20" },
  { id: "g-openmic-armadillo", title: "Tuesday Open Mic", venueId: "v-armadillo", date: "Tue Jul 7", time: "7:00 PM" },
];

// --------------------------------------------------------------------- feed

export const FEED_POSTS: FeedPost[] = [
  {
    id: "p-1",
    kind: "need-sub",
    author: { type: "band", id: "b-cedarrye" },
    text: "SOS, Austin. Our drummer's van gave out in Waco and tonight's residency is NOT cancelling. Need a country-comfortable drummer, brushes a plus. Charts ready, soundcheck 7:30.",
    ago: "2h",
    likes: 34,
    comments: 11,
    gigId: "g-cedarrye-rattlesnake",
    subFor: { instrument: "drums", date: "Tonight · 9:00 PM", payout: 150 },
  },
  {
    id: "p-2",
    kind: "gig",
    author: { type: "band", id: "b-moontower" },
    text: "EP RELEASE FRIDAY 🌙 'Porch Light' gets loud at the Blue Armadillo. First 50 through the door get a screen-printed poster Nina made in her kitchen.",
    ago: "4h",
    likes: 128,
    comments: 23,
    gigId: "g-moontower-armadillo",
  },
  {
    id: "p-3",
    kind: "video",
    author: { type: "musician", id: "m-dre" },
    text: "New reel: half-time shuffle breakdown. This one took 30 takes and one noise complaint.",
    ago: "5h",
    likes: 412,
    comments: 37,
    video: { id: "v-dre-2", title: "Half-time shuffle breakdown", durationSec: 51, plays: 8900, likes: 990, palette: ["#ef4444", "#1e1b4b"], tags: ["shuffle", "lesson"] },
    videoOwnerId: "m-dre",
  },
  {
    id: "p-4",
    kind: "open-mic",
    author: { type: "venue", id: "v-armadillo" },
    text: "Tuesday Open Mic sign-ups open at 6, music at 7. Backline provided (yes, real amps, no, not the broken one from last month — we fixed it).",
    ago: "8h",
    likes: 56,
    comments: 9,
    gigId: "g-openmic-armadillo",
  },
  {
    id: "p-5",
    kind: "gig",
    author: { type: "venue", id: "v-sunset" },
    text: "SATURDAY: Brass House ATX turns our ballroom into a block party. Nine musicians, four horns, zero chill. A few tickets left.",
    ago: "12h",
    likes: 203,
    comments: 31,
    gigId: "g-brasshouse-sunset",
  },
  {
    id: "p-6",
    kind: "news",
    author: { type: "venue", id: "v-rattlesnake" },
    text: "We're opening the back room for rehearsal rentals — $15/hr for Backline members, backline included. Weekday afternoons only for now.",
    ago: "1d",
    likes: 89,
    comments: 17,
  },
  {
    id: "p-7",
    kind: "video",
    author: { type: "musician", id: "m-ada" },
    text: "Someone asked how the run in the bridge works. Slowed it down. You're welcome and I'm sorry.",
    ago: "1d",
    likes: 634,
    comments: 52,
    video: { id: "v-ada-1", title: "Vocal run breakdown 🔥", durationSec: 26, plays: 22800, likes: 3400, palette: ["#d946ef", "#713f12"], tags: ["vocals", "gospel"] },
    videoOwnerId: "m-ada",
  },
  {
    id: "p-8",
    kind: "need-sub",
    author: { type: "band", id: "b-velvet" },
    text: "Velvet Hour needs an upright bassist for Thursday at Prickly Pear. Standards set — if you know 'Autumn Leaves' in two keys you're 80% there.",
    ago: "1d",
    likes: 21,
    comments: 6,
    gigId: "g-velvet-prickly",
    subFor: { instrument: "bass", date: "Thu Jul 9 · 7:30 PM", payout: 175 },
  },
  {
    id: "p-9",
    kind: "gig",
    author: { type: "band", id: "b-nightmarket" },
    text: "Saturday. Warehouse 512. New live set with real drums this time. Priya built a lighting rig that has its own weather system.",
    ago: "2d",
    likes: 176,
    comments: 28,
    gigId: "g-nightmarket-warehouse",
  },
  {
    id: "p-10",
    kind: "news",
    author: { type: "venue", id: "v-prickly" },
    text: "Reminder: we pay every artist a guarantee, every night, no 'exposure' math. Booking November now — send your reel through your Backline profile.",
    ago: "2d",
    likes: 342,
    comments: 44,
  },
  {
    id: "p-11",
    kind: "video",
    author: { type: "musician", id: "m-pri" },
    text: "Before/after from Friday's bar gig. Same stage, same band, $90 of haze and intention.",
    ago: "3d",
    likes: 289,
    comments: 33,
    video: { id: "v-pri-1", title: "Before/after: bar stage glow-up", durationSec: 29, plays: 10300, likes: 1600, palette: ["#a855f7", "#0e7490"], tags: ["lighting"] },
    videoOwnerId: "m-pri",
  },
  {
    id: "p-12",
    kind: "news",
    author: { type: "band", id: "b-brasshouse" },
    text: "We're looking for a regular FOH engineer — 2-3 gigs a month, real budget. Details on our open slots. Tell your favorite sound person.",
    ago: "3d",
    likes: 67,
    comments: 12,
  },
];

// ------------------------------------------------------- seed conversations

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "c-m-theo",
    musicianId: "m-theo",
    unread: 1,
    messages: [
      { id: "cm-1", from: "me", text: "Theo! Great hang at the jam last week. You still doing fill-in dates?", at: "Tue 4:12 PM" },
      { id: "cm-2", from: "them", text: "Always. Thursdays are tight (Velvet Hour) but everything else is fair game 🎹", at: "Tue 4:40 PM" },
      { id: "cm-3", from: "them", text: "Also — if you ever need synth bass instead of a bassist, I got you. Cheaper than two hires 😄", at: "Tue 4:41 PM" },
    ],
  },
  {
    id: "c-m-gus",
    musicianId: "m-gus",
    unread: 0,
    messages: [
      { id: "cm-4", from: "me", text: "Hey Gus — do you travel with your own console for rooms that only have a powered mixer?", at: "Mon 11:02 AM" },
      { id: "cm-5", from: "them", text: "Yep, X32 rack + stage box lives in my trunk. Add $40 and it's yours for the night.", at: "Mon 11:30 AM" },
    ],
  },
];

// ------------------------------------------------------------------ lookups

const musicianById = new Map(MUSICIANS.map((m) => [m.id, m]));
const bandById = new Map(BANDS.map((b) => [b.id, b]));
const venueById = new Map(VENUES.map((v) => [v.id, v]));
const gigById = new Map(GIGS.map((g) => [g.id, g]));

export function getMusician(id: string): Musician | undefined {
  return musicianById.get(id);
}
export function getBand(id: string): Band | undefined {
  return bandById.get(id);
}
export function getVenue(id: string): Venue | undefined {
  return venueById.get(id);
}
export function getGig(id: string): Gig | undefined {
  return gigById.get(id);
}

/** bands with an open slot for a given instrument */
export function bandsNeeding(instrumentId: string): Band[] {
  return BANDS.filter((b) => b.openSlots.some((s) => s.instrument === instrumentId));
}
